version: "3.8"

services:
  appvm:
    build:
      context: ../appvm
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env.appvm
    volumes:
      - ../apps:/appvm/apps
    depends_on:
      - relayer
  relayer:
    build:
      context: ../stream_relayer
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - ID=${ID}
#      - PION_LOG_TRACE=all
#      - PION_LOG_DEBUG=all
#      - PIONS_LOG_INFO=all
    env_file:
      - .env.relayer