version: "3.8"

services:
  appvm:
    build:
      context: ../appvm
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - videoport=${VIDEO_PORT}
      - audioport=${AUDIO_PORT}
      - wsport=${WS_PORT}
    env_file:
      - .env.appvm
    volumes:
      - ../apps:/appvm/apps
#      - winecfg:/root/.wine
#volumes:
#  winecfg: